trigger:
  branches:
    include:
      - dev

schedules:
  - cron: '0 3 * * *'
    displayName: 'Nightly Web Deploy'
    branches:
      include:
        - dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: environment
    value: 'dev'
  - group: 'Web'

extends:
  template: deploy-web-template.yaml
  parameters:
    environment: ${{ variables.environment }}
    envFile: '.env.dev'
