trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: environment
    value: 'prod'
  - group: 'Web'

extends:
  template: deploy-web-template.yaml
  parameters:
    environment: ${{ variables.environment }}
    envFile: '.env.prod'
