pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: environment
    value: 'qa'
  - group: 'Web'

extends:
  template: deploy-web-template.yaml
  parameters:
    environment: ${{ variables.environment }}
    envFile: '.env.qa'
